import { CoffeeShop } from './types';

export const MOCK_SHOPS: CoffeeShop[] = [
  {
    id: 'mock_001',
    name: 'Sightglass Coffee',
    address: '270 7th St, San Francisco, CA',
    neighborhood: 'SoMa',
    lat: 37.7759,
    lng: -122.4086,
    price_level: 3,
  },
  {
    id: 'mock_002',
    name: 'Ritual Coffee Roasters',
    address: '432B Octavia Blvd, San Francisco, CA',
    neighborhood: 'Hayes Valley',
    lat: 37.7763,
    lng: -122.4235,
    price_level: 3,
  },
  {
    id: 'mock_003',
    name: 'Verve Coffee Roasters',
    address: '833 S Spring St, Los Angeles, CA',
    neighborhood: 'Downtown LA',
    lat: 34.0440,
    lng: -118.2567,
    price_level: 3,
  },
  {
    id: 'mock_004',
    name: 'Go Get Em Tiger',
    address: '230 N Larchmont Blvd, Los Angeles, CA',
    neighborhood: 'Larchmont',
    lat: 34.0794,
    lng: -118.3237,
    price_level: 3,
  },
  {
    id: 'mock_005',
    name: 'Coava Coffee Roasters',
    address: '1300 SE Grand Ave, Portland, OR',
    neighborhood: 'Central Eastside',
    lat: 45.5176,
    lng: -122.6590,
    price_level: 2,
  },
  {
    id: 'mock_006',
    name: 'Heart Coffee Roasters',
    address: '537 SW 12th Ave, Portland, OR',
    neighborhood: 'Goose Hollow',
    lat: 45.5213,
    lng: -122.6842,
    price_level: 2,
  },
  {
    id: 'mock_007',
    name: 'Onyx Coffee Lab',
    address: '100 NW A St, Bentonville, AR',
    neighborhood: 'Downtown',
    lat: 36.3726,
    lng: -94.2088,
    price_level: 3,
  },
  {
    id: 'mock_008',
    name: 'La Colombe Coffee',
    address: '270 Lafayette St, New York, NY',
    neighborhood: 'Tribeca',
    lat: 40.7208,
    lng: -74.0034,
    price_level: 3,
  },
  {
    id: 'mock_009',
    name: "Toby's Estate Coffee",
    address: '125 N 6th St, Brooklyn, NY',
    neighborhood: 'Williamsburg',
    lat: 40.7172,
    lng: -73.9624,
    price_level: 3,
  },
  {
    id: 'mock_010',
    name: 'Birch Coffee',
    address: '750 6th Ave, New York, NY',
    neighborhood: 'Chelsea',
    lat: 40.7435,
    lng: -73.9973,
    price_level: 2,
  },
  {
    id: 'mock_011',
    name: 'Compass Coffee',
    address: '1535 7th St NW, Washington, DC',
    neighborhood: 'Shaw',
    lat: 38.9104,
    lng: -77.0215,
    price_level: 2,
  },
  {
    id: 'mock_012',
    name: 'Qualia Coffee',
    address: '3917 Georgia Ave NW, Washington, DC',
    neighborhood: 'Petworth',
    lat: 38.9398,
    lng: -77.0219,
    price_level: 2,
  },
  {
    id: 'mock_013',
    name: 'Houndstooth Coffee',
    address: '401 Congress Ave #100c, Austin, TX',
    neighborhood: 'Downtown Austin',
    lat: 30.2682,
    lng: -97.7434,
    price_level: 2,
  },
  {
    id: 'mock_014',
    name: 'Greater Goods Coffee',
    address: '2501 E 6th St, Austin, TX',
    neighborhood: 'East Austin',
    lat: 30.2610,
    lng: -97.7240,
    price_level: 2,
  },
  {
    id: 'mock_015',
    name: 'Methodical Coffee',
    address: '200 E Broad St, Greenville, SC',
    neighborhood: 'Downtown Greenville',
    lat: 34.8527,
    lng: -82.3973,
    price_level: 2,
  },
  {
    id: 'mock_016',
    name: 'Crema Coffee Roasters',
    address: '15 Hermitage Ave, Nashville, TN',
    neighborhood: 'Downtown Nashville',
    lat: 36.1567,
    lng: -86.7773,
    price_level: 2,
  },
  {
    id: 'mock_017',
    name: 'Merit Coffee',
    address: '2150 S Lamar Blvd, Austin, TX',
    neighborhood: 'South Lamar',
    lat: 30.2495,
    lng: -97.7666,
    price_level: 2,
  },
  {
    id: 'mock_018',
    name: 'Intelligentsia Coffee',
    address: '3922 Sunset Blvd, Los Angeles, CA',
    neighborhood: 'Silver Lake',
    lat: 34.0904,
    lng: -118.2678,
    price_level: 3,
  },
  {
    id: 'mock_019',
    name: 'Stumptown Coffee Roasters',
    address: '128 SW 3rd Ave, Portland, OR',
    neighborhood: 'Old Town',
    lat: 45.5234,
    lng: -122.6757,
    price_level: 2,
  },
  {
    id: 'mock_020',
    name: 'Blue Bottle Coffee',
    address: '66 Mint St, San Francisco, CA',
    neighborhood: 'Financial District',
    lat: 37.7857,
    lng: -122.4046,
    price_level: 3,
  },
];
